# Ashton Bloom - Computational Physics - HW 1

### Exercise 2.2: Altitude of a satellite

In [51]:
from math import pi

G = 6.67e-11
M = 5.97e24
R = 6371
T = float(input("Enter the number of seconds it takes to orbit the Earth: "))

h = ((G*M*(T**2))/(4*(pi**2)))**(1/3) - R

print ("The altitude of the satellite above the Earth is:",h, "Meters")

Enter the number of seconds it takes to orbit the Earth: 100
The altitude of the satellite above the Earth is: 459122.3446876864 Meters


In [50]:
T = 86400
h = ((G*M*(T**2))/(4*(pi**2)))**(1/3) - R
print ("The altitude of a satellite that orbits Earth everyday is:",h, "Meters")
T = 5400
h = ((G*M*(T**2))/(4*(pi**2)))**(1/3) - R
print ("The altitude of a satellite that orbits Earth every 90 minutes is:",h, "Meters")
T = 2700
h = ((G*M*(T**2))/(4*(pi**2)))**(1/3) - R
print ("The altitude of a satellite that orbits Earth every 45 minutes is:",h, "Meters")


The altitude of a satellite that orbits Earth everyday is: 42226909.90630111 Meters
The altitude of a satellite that orbits Earth every 90 minutes is: 6650321.355498997 Meters
The altitude of a satellite that orbits Earth every 45 minutes is: 4189439.832315313 Meters


We can conclude from these last three calculations that the quicker you want to orbit the Earth, the closer you have to be to the surface. Which makes sense when you think about rotational physics and the how the closer you are to the axis of rotation, the faster you rotate.

### Exercise 2.5: Quantum Potential Step

In [46]:
from math import sqrt

m = 9.11e-31
E = 10
V = 9
hbar = 6.5821e-16

K1 = sqrt(2*m*E)/hbar
K2 = sqrt(2*m*(E-V))/hbar

T = (4*K1*K2)/((K1+K2)**2)
R = ((K1-K2)/(K1+K2))**2

print("The transmission probability is: ",T)
print("The reflection probability is: ",R)
print("To check calculations, add T and R: ", T+R)

The transmission probability is:  0.7301261363877615
The reflection probability is:  0.26987386361223825
To check calculations, add T and R:  0.9999999999999998


Since the Transmission and Reflection probability approximately adds to 1, we can conclude that the calculations done are correct.

### Exercise 2.8: Suppose arrarys A and B are defined as follows

Upon executing the code the following code using arrays:

print(b/a+1) - The program will divide each data point of "b" by the corresponding data point in "a" and then add one.

print(b/(a+1)) - The program will divide each data point of "b" by the corresponding data point in "a" plus one.

print(1/a) - The program will divide 1 by each data point of "a", as long as that data point is nonzero.


In [49]:
import numpy as np

a = np.array([1,2,3,4],int)
b = np.array([2,4,6,8],int)

print(b/a+1)
print(b/(a+1))
print(1/a)

[3. 3. 3. 3.]
[1.         1.33333333 1.5        1.6       ]
[1.         0.5        0.33333333 0.25      ]


As we can see from the following executed code, our predictions were correct.

### Exercise 2.11: Binomial coefficients

In [28]:
import math

def binomial(n,k):
    return math.factorial(n)//(math.factorial(k)*(math.factorial(n - k)))

n = 1
k = 0

print("The binomial coeffcient calculation for n =", n , "and k =", k, "is:",binomial(n,k))
print("")

def pascal(o):
    for line in range(0,o):
        for inte in range(0, line+1):
            print(binomial(line,inte), "", end="")
        print()

o = 20
print("Pascal's nontriangle triangle:")
pascal(o)
print("")

n = 100
h = 60
print("Probability that coin is flipped heads exaclty 60 times:", binomial(n,h)/2**n)
print("")

probability = 0
for h in range(h,n+1):
    probability += binomial(n,h)/(2**n)
print("Probability that a coin is flipped heads 60 or more times:", probability)


The binomial coeffcient calculation for n = 1 and k = 0 is: 1

Pascal's nontriangle triangle:
1 
1 1 
1 2 1 
1 3 3 1 
1 4 6 4 1 
1 5 10 10 5 1 
1 6 15 20 15 6 1 
1 7 21 35 35 21 7 1 
1 8 28 56 70 56 28 8 1 
1 9 36 84 126 126 84 36 9 1 
1 10 45 120 210 252 210 120 45 10 1 
1 11 55 165 330 462 462 330 165 55 11 1 
1 12 66 220 495 792 924 792 495 220 66 12 1 
1 13 78 286 715 1287 1716 1716 1287 715 286 78 13 1 
1 14 91 364 1001 2002 3003 3432 3003 2002 1001 364 91 14 1 
1 15 105 455 1365 3003 5005 6435 6435 5005 3003 1365 455 105 15 1 
1 16 120 560 1820 4368 8008 11440 12870 11440 8008 4368 1820 560 120 16 1 
1 17 136 680 2380 6188 12376 19448 24310 24310 19448 12376 6188 2380 680 136 17 1 
1 18 153 816 3060 8568 18564 31824 43758 48620 43758 31824 18564 8568 3060 816 153 18 1 
1 19 171 969 3876 11628 27132 50388 75582 92378 92378 75582 50388 27132 11628 3876 969 171 19 1 

Probability that coin is flipped heads exaclty 60 times: 0.010843866711637987

Probability that a coin is flipped he

We can see that when K = 0, it outputs 1

While it may not be formatted like an actual triangle, we can see the the numbers the code prints is that of Pascal's triangle.

By calculating the binomial coefficient with n = 100 and h = 60, we can see how many different combinations there are that will get us at least 60 heads, so all we have to do is then divide by 2^n power. We come up with this by recognizing that each flip has "2" possibilities, heads or tails, and so we raise 2^n power; which represents each and every combination of heads and tails we could possibly have. Meaing our calculation is how many possible configurations of at least 60 heads (binomial coefficient) and then every possible head/tail combination. Which then gives us the answer of 0.0108...

To get the probability of the at least 60 or more heads, we apply the same logic that we just used to calculate exactly 60 heads. To do this, we do the exact same calculations (binomial coefficient divided by all possible head/tail combinations) then add all the end results into a variable called probability. If we analyze this result, we can see that you have a greater chance of getting 60 or more heads than exactly 60 heads. Which makes sense since 60 or more is a less restrictive constraint than exactly 60.

### Exercise 2.13: Recursion

In [34]:
def catalan(n):
    if n==0:
        return 1
    else:
        return ((4*n-2)/(n+1))*catalan(n-1)

n = 100

print("The Catalan number using n =", n, "is:", catalan(n))

def gcd(m,n):
    if n == 0:
        return m
    else:
        return gcd(n,m%n)
m = 108
n = 192

print("The Greatest Common Denominator using m =", m, "and n =", n, "is:", gcd(m,n))

The Catalan number using n = 100 is: 8.965199470901317e+56
The Greatest Common Denominator using m = 108 and n = 192 is: 12


Since, the code does not error and the formula for calculating the catalan number using the given equation works without the "catalan(n-1)" and gives a different answer with it, I am assuming that calculation for the catalan n = 100 is correct.

We can very quickly check the greatest common denominator calculation using something easy such as "4" and "8" and it outputs a GCD of "4" which we know is correct, so we can safely assume that the calculation for 108 and 192 is correct.